defmodule Consensus.Voting.Participant do
  @moduledoc """
  One person in one activity group's vote.

  A participant is either a **guest** (`kind: :guest`, no account) or a signed-in
  **user** (`kind: :user`, `user_id` set). `kind` is recorded permanently rather than
  derived from `user_id`, because a user's account can later be deleted — the
  reference is `ON DELETE SET NULL` — and the record of what kind of voter a vote came
  from must survive that.

  `display_name` is optional: `nil` means anonymous. It is never stored as a blank
  string — a blank or whitespace-only name is normalised to `nil` by `changeset/2`, so
  "anonymous" has exactly one representation in the database and callers never have to
  test for both.

  `token` is the browser's claim on this row. It is 32 bytes of `:crypto.strong_rand_bytes`
  URL-encoded, generated by `Consensus.Voting.create_participant/2` and **never castable**
  — nothing a client sends can choose or change it. It goes in the Phoenix session so a
  guest can return to the ballot or the results without an account.

  `voted_at` is the ballot lock: `nil` means "has not submitted", non-nil means the
  ballot is cast and locked (D-036 — there is no "change my ranking"). It is likewise
  absent from `changeset/2`'s `cast/3` and is only ever set by
  `Consensus.Voting.cast_ballot/3`, inside the transaction that writes the vote rows.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @kinds [:guest, :user]
  @max_display_name_length 40

  @doc "Every kind of participant."
  def kinds, do: @kinds

  @doc """
  Longest display name a participant may type.

  Exposed as a function for the same reason `Activity.max_description_length/0` is:
  per CLAUDE.md invariant 11 a free-text field gets no `maxlength` attribute, and the
  screen renders a live counter that reads *this* number so the browser and the
  changeset can never disagree about what fits.
  """
  def max_display_name_length, do: @max_display_name_length

  schema "participants" do
    field :display_name, :string
    field :kind, Ecto.Enum, values: @kinds
    field :token, :string
    field :voted_at, :utc_datetime

    belongs_to :group, Consensus.Activities.Group
    belongs_to :user, Consensus.Accounts.User

    has_many :votes, Consensus.Voting.Vote

    timestamps(type: :utc_datetime)
  end

  @doc """
  Changeset for creating a participant.

  Casts exactly `[:display_name, :kind]`. `:group_id`, `:user_id`, `:token` and
  `:voted_at` are all set programmatically on the struct by `Consensus.Voting` and are
  deliberately absent — the same shape `Consensus.Accounts.User.registration_changeset/3`
  uses to keep `:is_admin` out, and `Consensus.Activities.Group.changeset/2` uses to keep
  `:status` out.

  `:kind` and `:user_id` must agree: `:user` requires a `user_id`, `:guest` requires its
  absence. That is validated here rather than trusted, because `kind` *is* castable and
  `user_id` is not, so a caller could otherwise mint a `kind: :user` row with no account
  behind it.
  """
  def changeset(participant, attrs) do
    participant
    |> cast(attrs, [:display_name, :kind])
    |> update_change(:display_name, &blank_to_nil/1)
    |> validate_required([:kind])
    |> validate_inclusion(:kind, @kinds)
    |> validate_length(:display_name, max: @max_display_name_length)
    |> validate_kind_matches_user()
    |> validate_required([:token])
    |> foreign_key_constraint(:group_id)
    |> foreign_key_constraint(:user_id)
    |> unique_constraint(:token)
    |> unique_constraint(:user_id, name: :participants_group_id_user_id_index)
  end

  @doc "True once this participant's ballot has been cast. The ballot is then locked."
  def voted?(%__MODULE__{voted_at: nil}), do: false
  def voted?(%__MODULE__{}), do: true

  @doc """
  What to show in the avatar row for this participant: a single upper-case grapheme,
  or `\"?\"` for an anonymous participant.
  """
  def initial(%__MODULE__{display_name: nil}), do: "?"

  def initial(%__MODULE__{display_name: name}) do
    case String.first(String.trim(name)) do
      nil -> "?"
      grapheme -> String.upcase(grapheme)
    end
  end

  defp validate_kind_matches_user(changeset) do
    kind = get_field(changeset, :kind)
    user_id = get_field(changeset, :user_id)

    case {kind, user_id} do
      {:user, nil} -> add_error(changeset, :user_id, "is required for a signed-in participant")
      {:guest, nil} -> changeset
      {:guest, _id} -> add_error(changeset, :kind, "must be :user when a user_id is present")
      _ -> changeset
    end
  end

  defp blank_to_nil(nil), do: nil

  defp blank_to_nil(value) when is_binary(value) do
    case String.trim(value) do
      "" -> nil
      trimmed -> trimmed
    end
  end

  defp blank_to_nil(value), do: value
end
