import Config

# Configure your database
config :consensus, Consensus.Repo,
  database: Path.expand("../consensus_dev.db", __DIR__),
  # ONE connection, deliberately — see D-038. SQLite allows a single write transaction
  # across the whole file, so extra pool slots do not buy write concurrency; they
  # manufacture contention for a lock that was never shareable, and SQLite's busy
  # handler is documented to be unfair about who wins. Measured on a 15-voter deadline
  # burst: pool 5 → p95 25,762ms; pool 1 → p95 10.6ms. Reads got faster too.
  pool_size: 1,
  # Match production so "database is locked" cannot be a production-only surprise.
  # `BEGIN IMMEDIATE` rather than ecto_sqlite3's default `BEGIN DEFERRED`. A deferred
  # transaction takes no write lock at `BEGIN` and asks for one on its first write — and if
  # another writer holds it by then, SQLite cannot wait (this connection already holds a read
  # snapshot, so blocking could deadlock the pair). It returns `SQLITE_BUSY` at once and the
  # `busy_timeout` handler never runs. Taking the lock up front is what lets `busy_timeout`
  # do its job, so two simultaneous organizer writes queue instead of one 500ing. D-033.
  default_transaction_mode: :immediate,
  journal_mode: :wal,
  busy_timeout: 5_000,
  # Pinned rather than inherited. `:normal` is already ecto_sqlite3's and exqlite's
  # default, so this changes nothing today — it makes the durability trade a decision
  # instead of a default nobody chose. With WAL, `:normal` fsyncs at checkpoint rather
  # than at every commit: a process crash cannot corrupt or lose a committed
  # transaction, only a host power loss or kernel panic can. D-038.
  synchronous: :normal,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :consensus, ConsensusWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dh4jr+WZWDVECFoyGt4iKU/MFvneploJ3o3Jdi9s865V4y2TdpzZspt68mZK77JM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:consensus, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:consensus, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# The Assisted Add in dev answers from the scripted provider (dev/support/
# scripted_provider.ex — its moduledoc documents the QUERY VOCABULARY: which typed
# name produces one match, three matches, no match, an error, a timeout, or a
# multi-second SLOW answer) so browser and pixel work never depends on the public
# Overpass instance. Same registry shape as prod, different data — invariant 12
# holds either way. Start dev with ASSIST_LIVE=1 to swap the real Overpass adapter
# back in (config/runtime.exs).
config :consensus, Consensus.Discovery,
  providers: %{"restaurant" => {Consensus.Dev.ScriptedProvider, []}}

# Both knobs optional (these are the defaults): delay_ms is the shimmer-visible
# pause before every answer, slow_ms is the `slow` query's screenshot hold.
config :consensus, Consensus.Dev.ScriptedProvider, delay_ms: 900, slow_ms: 5_000

# Enable dev routes for dashboard and mailbox
config :consensus, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n", metadata: [:cid]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
