defmodule Consensus.Repo.Migrations.CreateUsersAuthTables do
  use Ecto.Migration

  # Generated by `mix phx.gen.auth`. The `username` and `is_admin` columns were folded
  # into this migration (rather than added by a follow-up migration) because this is the
  # app's initial, never-deployed schema, and because SQLite cannot add a `NOT NULL`
  # column with a `UNIQUE` index to a populated table without a table rewrite.
  # See docs/decisions.md.
  def change do
    create table(:users) do
      add :email, :string, null: false, collate: :nocase
      add :username, :string, null: false, collate: :nocase
      add :hashed_password, :string
      add :confirmed_at, :utc_datetime
      add :is_admin, :boolean, null: false, default: false

      timestamps(type: :utc_datetime)
    end

    create unique_index(:users, [:email])
    create unique_index(:users, [:username])

    create table(:users_tokens) do
      add :user_id, references(:users, on_delete: :delete_all), null: false
      add :token, :binary, null: false, size: 32
      add :context, :string, null: false
      add :sent_to, :string
      add :authenticated_at, :utc_datetime

      timestamps(type: :utc_datetime, updated_at: false)
    end

    create index(:users_tokens, [:user_id])
    create unique_index(:users_tokens, [:context, :token])
  end
end
